Fix missing BSD-style type definitions on Linux
Add sys/types.h and sys/socket.h includes for Linux platform to provide
u_char, u_short, and other BSD-style type definitions used by ntpdcontrol.h

This fixes compilation errors:
- error: unknown type name 'u_char'
- error: unknown type name 'u_short'

These types are defined in sys/types.h on Linux but were only being
included for BSD-based systems.

Fixes CI Build #22384241471 (Build #68)